#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 cat-pretrade-data-model contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Convert Delta Lake DDL -> Hive 3.x DDL.

Transformations:
 USING DELTA -> STORED AS PARQUET
 GENERATED ALWAYS AS (current_timestamp) -> (drop the clause)
 DEFAULT <expr> -> (drop inline default)
 'delta.autoOptimize.*' TBLPROPERTIES -> drop
 'delta.columnMapping.mode' = 'name' -> drop
 'delta.enableChangeDataFeed' = 'true' -> drop
 'compression.codec' = 'zstd' -> 'parquet.compression' = 'ZSTD'

Run:
 python3 _delta_to_hive.py
Generates one *_hive.sql per *_delta.sql source (excluding split 01a/b/c, 02a/b/c).
"""
from __future__ import annotations
import glob
import os
import re
from pathlib import Path

SRC_DIR = Path(__file__).parent
OUT_DIR = SRC_DIR.parent / "expanded-model-hive"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Source files - use combined 01_, 02_ (not 01a/b/c or 02a/b/c)
SRC_FILES = sorted([
 f for f in SRC_DIR.glob("*.sql")
 if not any(tag in f.name for tag in ("01a_", "01b_", "01c_",
 "02a_", "02b_", "02c_"))
 and "_delta" in f.name
])

DELTA_TBLPROPS = {
 "delta.autoOptimize.optimizeWrite",
 "delta.autoOptimize.autoCompact",
 "delta.columnMapping.mode",
 "delta.enableChangeDataFeed",
 "compression.codec", # replaced with parquet.compression
 "description", # keep generic - translate
 "subject_area", # keep
 "source_lineage", # keep
}

def convert(sql: str) -> str:
 # 1. Drop GENERATED ALWAYS AS (current_timestamp) - keep column type + COMMENT
 sql = re.sub(
 r"GENERATED ALWAYS AS \(current_timestamp\(\)\)",
 "",
 sql,
)
 # 2. Drop inline DEFAULT clauses (Hive doesn't support column-level defaults)
 sql = re.sub(
 r"\bDEFAULT\s+(?:DATE'[^']*'|'[^']*'|[A-Z_]+\([^)]*\)|[-\d.]+|TRUE|FALSE|NULL|0)\b",
 "",
 sql,
 flags=re.IGNORECASE,
)
 # 3. USING DELTA -> STORED AS PARQUET
 sql = re.sub(r"USING DELTA", "STORED AS PARQUET", sql)
 # 4. Fix TBLPROPERTIES - drop delta-specific, translate compression
 def _fix_tblprops(match: re.Match) -> str:
 body = match.group(1)
 kept: list[str] = []
 for line in body.splitlines:
 stripped = line.strip.rstrip(",")
 if not stripped:
 continue
 if stripped.startswith("'delta.autoOptimize"):
 continue
 if stripped.startswith("'delta.columnMapping"):
 continue
 if stripped.startswith("'delta.enableChangeDataFeed"):
 continue
 if stripped.startswith("'compression.codec'"):
 kept.append(" 'parquet.compression' = 'ZSTD'")
 continue
 kept.append(" " + stripped)
 return "TBLPROPERTIES (\n" + ",\n".join(kept) + "\n)"

 sql = re.sub(
 r"TBLPROPERTIES\s*\(\s*(.*?)\s*\)",
 _fix_tblprops,
 sql,
 flags=re.DOTALL,
)
 # 5. Clean up double spaces and trailing whitespace on lines
 sql = re.sub(r"[ \t]+\n", "\n", sql)
 sql = re.sub(r"[ \t]{3,}", " ", sql)
 return sql

def header(relpath: str) -> str:
 return (
 "-- " + "=" * 72 + "\n"
 f"-- Hive 3.x variant of {relpath}\n"
 "-- Auto-generated by _delta_to_hive.py - do NOT hand-edit.\n"
 "-- Changes from Delta:\n"
 "-- USING DELTA -> STORED AS PARQUET\n"
 "-- GENERATED ALWAYS AS (current_timestamp) removed (populate via ETL)\n"
 "-- DEFAULT clauses removed (enforce via ETL)\n"
 "-- delta.* TBLPROPERTIES removed\n"
 "-- compression.codec -> parquet.compression\n"
 "-- " + "=" * 72 + "\n\n"
)

def main -> None:
 for src in SRC_FILES:
 out = OUT_DIR / src.name.replace("_delta.sql", "_hive.sql")
 original = src.read_text
 converted = header(src.name) + convert(original)
 out.write_text(converted)
 print(f" {out.name} ({len(converted):,} bytes)")
 print(f"\nGenerated {len(SRC_FILES)} Hive-variant files in {OUT_DIR}")

if __name__ == "__main__":
 main
