"""DEPRECATED. This file was a one-time converter generated by the
v2.0.0 build phase as syntactically-invalid pseudo-code. Its outputs
(the dialect-specific DDL files and .drawio diagrams) are checked in
to the repo and are now the source of truth.

Do not run. If you need to regenerate from a Delta source, write a new
converter against the current source-of-truth DDL.
"""
raise RuntimeError(
    "This converter is deprecated. The DDL / diagram outputs it "
    "would have produced are checked in directly."
)
