-- Simple-option Gold-layer DDL (Apache Hive).

CREATE TABLE IF NOT EXISTS gold.fact_option_order_events (
    option_event_sk             BIGINT,
    event_dts                   TIMESTAMP,
    date_sk                     BIGINT,
    instrument_sk               BIGINT,
    party_sk                    BIGINT,
    trader_sk                   BIGINT,
    desk_sk                     BIGINT,
    account_sk                  BIGINT,
    venue_sk                    BIGINT,
    event_type_sk               BIGINT,
    option_id                   STRING,
    cat_order_id                STRING,
    cat_event_code              STRING COMMENT 'CHECK in Section 5.1 order/quote/lifecycle codes',
    side                        STRING,
    price                       DECIMAL(38, 18),
    quantity                    DECIMAL(38, 18),
    leaves_qty                  DECIMAL(38, 18),
    cancel_qty                  DECIMAL(38, 18),
    order_type                  STRING,
    time_in_force               STRING,
    trading_session             STRING,
    open_close_indicator        STRING,
    handling_instructions       STRING,
    net_price                   DECIMAL(38, 18),
    parent_order_id             STRING,
    prior_order_id              STRING,
    initiator                   STRING,
    trigger_price               DECIMAL(38, 18),
    source_file                 STRING,
    source_batch_id             STRING,
    dv2_source_hk               STRING,
    quality_outcome             STRING
)
PARTITIONED BY (event_date DATE)
STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS gold.fact_option_executions (
    option_execution_sk         BIGINT,
    event_dts                   TIMESTAMP,
    date_sk                     BIGINT,
    instrument_sk               BIGINT,
    party_sk                    BIGINT,
    venue_sk                    BIGINT,
    event_type_sk               BIGINT,
    option_id                   STRING,
    cat_event_code              STRING COMMENT 'CHECK in MOOT,MOOF,MOOFS,MOFA',
    trade_id                    STRING,
    fulfillment_id              STRING,
    prior_fulfillment_id        STRING,
    quantity                    DECIMAL(38, 18),
    price                       DECIMAL(38, 18),
    capacity                    STRING,
    tape_trade_id               STRING,
    market_center_id            STRING,
    side_details_ind            STRING,
    clearing_firm               STRING,
    fulfillment_link_type       STRING,
    cancel_flag                 BOOLEAN,
    cancel_timestamp            TIMESTAMP,
    multi_leg_ind               BOOLEAN,
    source_file                 STRING,
    source_batch_id             STRING,
    dv2_source_hk               STRING,
    quality_outcome             STRING
)
PARTITIONED BY (event_date DATE)
STORED AS PARQUET;

CREATE TABLE IF NOT EXISTS gold.fact_option_allocations (
    option_allocation_sk        BIGINT,
    event_dts                   TIMESTAMP,
    date_sk                     BIGINT,
    instrument_sk               BIGINT,
    party_sk                    BIGINT,
    account_sk                  BIGINT,
    event_type_sk               BIGINT,
    option_id                   STRING,
    cat_event_code              STRING COMMENT 'CHECK in MOPA,MOAA',
    allocation_id               STRING,
    prior_allocation_id         STRING,
    side                        STRING,
    quantity                    DECIMAL(38, 18),
    price                       DECIMAL(38, 18),
    firm_designated_id          STRING,
    new_order_fdid              STRING,
    correspondent_crd           BIGINT,
    occ_clearing_member_id      STRING,
    trade_date                  DATE,
    settlement_date             DATE,
    allocation_type             STRING,
    institution_flag            BOOLEAN,
    account_holder_type         STRING,
    cancel_flag                 BOOLEAN,
    cancel_timestamp            TIMESTAMP,
    source_file                 STRING,
    source_batch_id             STRING,
    dv2_source_hk               STRING,
    quality_outcome             STRING
)
PARTITIONED BY (event_date DATE)
STORED AS PARQUET;
