-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 cat-pretrade-data-model contributors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- ========================================================================
-- Hive 3.x variant of 05_pretrade_model_delta.sql
-- Auto-generated by _delta_to_hive.py - do NOT hand-edit.
-- Changes from Delta:
-- USING DELTA -> STORED AS PARQUET
-- GENERATED ALWAYS AS (current_timestamp) removed (populate via ETL)
-- DEFAULT clauses removed (enforce via ETL)
-- delta.* TBLPROPERTIES removed
-- compression.codec -> parquet.compression
-- ========================================================================

-- ============================================================================
-- File: 05_pretrade_model_delta.sql
-- Purpose: Enterprise Pre-Trade Stage Model (5 entities, Delta Lake)
-- Scope: RFQ lifecycle, quote publication, RFE, IOI
-- CAT Events Covered: MEQR (quote_request), MEQS (quote_event)
-- FIX Messages: 35=R (QuoteRequest), 35=S (Quote), 35=6 (IOI)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Entity 1 of 5: quote_request (NEW - CAT event MEQR)
-- Request for Quote (RFQ) - FIX QuoteRequest 35=R
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quote_request (
 quote_request_id STRING NOT NULL COMMENT 'UUID v4 - Primary key',
 cat_event_type STRING NOT NULL DEFAULT 'MEQR' COMMENT 'CAT event taxonomy - fixed to MEQR (Quote Received)',
 quote_req_id STRING NOT NULL COMMENT 'FIX tag 131 QuoteReqID - business key for hub_quote_request in DV2',
 requesting_party_role_id STRING NOT NULL COMMENT 'FK to party_role.party_role_id - client / buy-side requesting the quote',
 instrument_id STRING NOT NULL COMMENT 'FK to instrument.instrument_id - subject of the RFQ',
 side STRING NOT NULL COMMENT 'BUY, SELL, TWO_WAY (client requesting both bid and ask)',
 quantity DECIMAL(18,4) NOT NULL COMMENT 'Requested quantity (may be indicative)',
 quote_type STRING NOT NULL COMMENT 'INDICATIVE, TRADEABLE, RESTRICTED_TRADEABLE (FIX tag 537)',
 expire_timestamp TIMESTAMP COMMENT 'RFQ expiration - quotes received after this time are void (FIX tag 126)',
 received_timestamp TIMESTAMP NOT NULL COMMENT 'When RFQ was received (CAT receivedTimestamp)',
 solicited_dealers STRING COMMENT 'JSON array of dealer party_role_ids solicited for quotes (supports one-to-many RFQ)',
 request_status STRING NOT NULL COMMENT 'OPEN, ANSWERED, PARTIALLY_ANSWERED, EXPIRED, CANCELLED, REJECTED',
 venue_id STRING COMMENT 'FK to venue.venue_id - RFQ platform (e.g., MarketAxess, Tradeweb) or NULL for bilateral',
 currency STRING COMMENT 'ISO 4217 currency code (for fixed income / FX RFQs)',
 settlement_date DATE COMMENT 'Requested settlement date',
 event_date DATE NOT NULL COMMENT 'Partition date - typically received_timestamp::DATE',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Request for Quote (RFQ) - CAT event MEQR / FIX 35=R; dominant in fixed income, OTC derivatives, FX, structured products; one RFQ can solicit quotes from multiple dealers'
PARTITIONED BY (event_date)
TBLPROPERTIES (
 'description' = 'RFQ - MEQR / FIX 35=R',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'pretrade',
 'source_lineage' = ' section Pre-Trade Stage - quote_request'
);

-- Z-ORDER BY (quote_req_id, requesting_party_role_id, instrument_id, request_status)

-- ----------------------------------------------------------------------------
-- Entity 2 of 5: quote_event (NEW - CAT event MEQS)
-- Two-way quote published - FIX Quote 35=S
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quote_event (
 quote_event_id STRING NOT NULL COMMENT 'UUID v4 - Primary key',
 cat_event_type STRING NOT NULL DEFAULT 'MEQS' COMMENT 'CAT event taxonomy - fixed to MEQS (Quote Sent)',
 quote_id STRING NOT NULL COMMENT 'FIX tag 117 QuoteID - business key for hub_quote in DV2',
 quote_request_id STRING COMMENT 'FK to quote_request.quote_request_id - NULL if unsolicited streaming quote',
 quoting_party_role_id STRING NOT NULL COMMENT 'FK to party_role.party_role_id - market maker / dealer publishing the quote',
 instrument_id STRING NOT NULL COMMENT 'FK to instrument.instrument_id - subject of the quote',
 bid_price DECIMAL(18,6) COMMENT 'Bid price (dealer willing to buy at)',
 ask_price DECIMAL(18,6) COMMENT 'Ask price (dealer willing to sell at)',
 bid_quantity DECIMAL(18,4) COMMENT 'Bid size',
 ask_quantity DECIMAL(18,4) COMMENT 'Ask size',
 quote_condition STRING NOT NULL COMMENT 'FIRM (binding), INDICATIVE (non-binding), SUBJECT (subject to last look) - FIX tag 276',
 validity_start TIMESTAMP COMMENT 'Quote validity begins (FIX tag 62 ValidUntilTime - start component)',
 validity_end TIMESTAMP COMMENT 'Quote validity ends (FIX tag 62 ValidUntilTime)',
 published_timestamp TIMESTAMP NOT NULL COMMENT 'When quote was published (CAT publishedTimestamp)',
 quote_type STRING NOT NULL COMMENT 'TRADEABLE, INDICATIVE, RESTRICTED (FIX tag 537)',
 quote_status STRING NOT NULL COMMENT 'ACTIVE, EXECUTED, CANCELLED, EXPIRED, SUPERSEDED',
 prior_quote_id STRING COMMENT 'Self-FK to quote_event.quote_event_id - prior version when quote is updated/superseded',
 venue_id STRING COMMENT 'FK to venue.venue_id - publication venue (RFQ platform, streaming venue)',
 quoting_idqs STRING COMMENT 'CAT IDQS - identifier of quote source system (CAT-specific field)',
 currency STRING COMMENT 'ISO 4217 currency code of bid/ask prices',
 event_date DATE NOT NULL COMMENT 'Partition date - typically published_timestamp::DATE',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Two-way quote - CAT event MEQS / FIX 35=S; market-maker bid/ask with validity window; critical for best-execution audit and CAT quote linkage on resulting trades via execution.quote_event_id'
PARTITIONED BY (event_date)
TBLPROPERTIES (
 'description' = 'Quote event - MEQS / FIX 35=S',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'pretrade',
 'source_lineage' = ' section Pre-Trade Stage - quote_event'
);

-- Z-ORDER BY (quote_id, quote_request_id, quoting_party_role_id, quote_status)

-- ----------------------------------------------------------------------------
-- Entity 3 of 5: quote_response (NEW)
-- Junction: RFQ ↔ Quote - many-to-many linkage
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quote_response (
 quote_response_id STRING NOT NULL COMMENT 'UUID v4 - Primary key',
 quote_request_id STRING NOT NULL COMMENT 'FK to quote_request.quote_request_id',
 quote_event_id STRING NOT NULL COMMENT 'FK to quote_event.quote_event_id - the quote sent in response',
 responding_party_role_id STRING NOT NULL COMMENT 'FK to party_role.party_role_id - dealer that responded',
 response_timestamp TIMESTAMP NOT NULL COMMENT 'When response was received by requester',
 response_rank INT COMMENT 'Best-price ranking among responses (1 = best) - computed at RFQ close',
 selected_flag BOOLEAN NOT NULL COMMENT 'TRUE if this quote was hit / selected by the requester',
 selection_timestamp TIMESTAMP COMMENT 'When requester selected this quote (NULL if not selected)',
 rejection_reason STRING COMMENT 'PRICE, SIZE, STALE, COMPLIANCE, OTHER - populated when selected_flag = FALSE and rejected explicitly',
 event_date DATE NOT NULL COMMENT 'Partition date',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Junction tracking which quote(s) were sent in response to which RFQ - supports many-to-many: one RFQ ↔ many quotes, one streaming quote ↔ many RFQs'
PARTITIONED BY (event_date)
TBLPROPERTIES (
 'description' = 'Quote response junction - RFQ ↔ quote',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'pretrade',
 'source_lineage' = ' section Pre-Trade Stage - quote_response'
);

-- Z-ORDER BY (quote_request_id, quote_event_id, selected_flag)

-- ----------------------------------------------------------------------------
-- Entity 4 of 5: request_for_execution (NEW)
-- Client request to execute (distinct from RFQ) - agency execution flow
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS request_for_execution (
 rfe_id STRING NOT NULL COMMENT 'UUID v4 - Primary key',
 requesting_party_role_id STRING NOT NULL COMMENT 'FK to party_role.party_role_id - client sending the RFE',
 receiving_party_role_id STRING NOT NULL COMMENT 'FK to party_role.party_role_id - broker/dealer receiving the RFE',
 instrument_id STRING NOT NULL COMMENT 'FK to instrument.instrument_id',
 side STRING NOT NULL COMMENT 'BUY, SELL',
 requested_quantity DECIMAL(18,4) NOT NULL COMMENT 'Quantity requested for execution',
 price_type STRING NOT NULL COMMENT 'MARKET, LIMIT, VWAP, TWAP, CLOSE, POV (percentage of volume)',
 limit_price DECIMAL(18,6) COMMENT 'Limit price when price_type = LIMIT',
 urgency STRING COMMENT 'NORMAL, URGENT, FLASH - drives routing prioritization',
 instruction_text STRING COMMENT 'Free-text special instructions from client',
 rfe_status STRING NOT NULL COMMENT 'RECEIVED, ACCEPTED, REJECTED, EXPIRED, CANCELLED',
 rejection_reason STRING COMMENT 'Reason code when rfe_status = REJECTED',
 received_timestamp TIMESTAMP NOT NULL COMMENT 'When broker received the RFE',
 response_timestamp TIMESTAMP COMMENT 'When broker accepted/rejected the RFE',
 currency STRING COMMENT 'ISO 4217 currency code',
 venue_hint STRING COMMENT 'Preferred execution venue MIC (client hint, not binding)',
 event_date DATE NOT NULL COMMENT 'Partition date - typically received_timestamp::DATE',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Request for Execution (RFE) - client asks broker to execute a trade (cash equities/agency flow); distinct from RFQ (RFE = execute this; RFQ = price this); precedes order creation'
PARTITIONED BY (event_date)
TBLPROPERTIES (
 'description' = 'Request for Execution - agency execution intent',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'pretrade',
 'source_lineage' = ' section Pre-Trade Stage - request_for_execution'
);

-- Z-ORDER BY (requesting_party_role_id, instrument_id, rfe_status)

-- ----------------------------------------------------------------------------
-- Entity 5 of 5: indication_of_interest (NEW - FIX IOI 35=6)
-- Broker-initiated non-binding indication to buy/sell
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS indication_of_interest (
 ioi_id STRING NOT NULL COMMENT 'UUID v4 - Primary key',
 ioi_ref_id STRING NOT NULL COMMENT 'FIX tag 23 IOIID - broker-assigned IOI reference',
 originator_party_role_id STRING NOT NULL COMMENT 'FK to party_role.party_role_id - broker/dealer publishing the IOI',
 instrument_id STRING NOT NULL COMMENT 'FK to instrument.instrument_id',
 side STRING NOT NULL COMMENT 'BUY, SELL, UNDISCLOSED',
 quantity_type STRING NOT NULL COMMENT 'EXACT, RANGE, UNDISCLOSED (FIX tag 27 IOIQty)',
 min_quantity DECIMAL(18,4) COMMENT 'Minimum quantity (when quantity_type = RANGE)',
 max_quantity DECIMAL(18,4) COMMENT 'Maximum quantity (when quantity_type = RANGE or EXACT)',
 price_indication DECIMAL(18,6) COMMENT 'Indicative price level',
 ioi_type STRING NOT NULL COMMENT 'NATURAL (client-originated), FACILITATION (broker capital), CROSSING (internal cross opportunity)',
 ioi_qualifier STRING COMMENT 'FIX tag 130 IOIQualifier: AON (All-or-None), AT_CLOSE, VWAP, CROSS, FACILITATION, MARKET_CLOSE',
 ioi_natural_flag BOOLEAN COMMENT 'FIX tag 25 IOINaturalFlag - TRUE if IOI represents natural client-side interest',
 validity STRING NOT NULL COMMENT 'DAY, GTC (Good-Till-Cancel), IOC (Immediate-or-Cancel)',
 ioi_status STRING NOT NULL COMMENT 'ACTIVE, WITHDRAWN, EXPIRED, CANCELLED, CONVERTED (to order)',
 published_timestamp TIMESTAMP NOT NULL COMMENT 'When IOI was published',
 withdrawn_timestamp TIMESTAMP COMMENT 'When IOI was withdrawn (NULL if active)',
 venue_id STRING COMMENT 'FK to venue.venue_id - publication venue (IOI network, Bloomberg, direct FIX)',
 currency STRING COMMENT 'ISO 4217 currency code',
 event_date DATE NOT NULL COMMENT 'Partition date - typically published_timestamp::DATE',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Indication of Interest (IOI) - FIX 35=6; broker-initiated non-binding advertising of inventory or natural client interest; can trigger RFEs, RFQs, or direct orders'
PARTITIONED BY (event_date)
TBLPROPERTIES (
 'description' = 'Indication of Interest - FIX 35=6',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'pretrade',
 'source_lineage' = ' section Pre-Trade Stage - indication_of_interest'
);

-- Z-ORDER BY (originator_party_role_id, instrument_id, ioi_status)

-- ============================================================================
-- END OF FILE - 5 CREATE TABLE statements
-- ============================================================================
