-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 cat-pretrade-data-model contributors
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- ========================================================================
-- Hive 3.x variant of 13_reference_tables_delta.sql
-- Auto-generated by _delta_to_hive.py - do NOT hand-edit.
-- Changes from Delta:
-- USING DELTA -> STORED AS PARQUET
-- GENERATED ALWAYS AS (current_timestamp) removed (populate via ETL)
-- DEFAULT clauses removed (enforce via ETL)
-- delta.* TBLPROPERTIES removed
-- compression.codec -> parquet.compression
-- ========================================================================

-- ============================================================================
-- File: 13_reference_tables_delta.sql
-- Purpose: Enterprise Reference Tables (16 entities, Delta Lake)
-- Scope: Enum enforcement + ISO/industry standard code tables
-- Pattern: All ref_* tables share common shape: code, name, description,
-- category, effective_start_date, effective_end_date, is_active,
-- source_authority, source_version, last_updated_date, record_source,
-- load_date. PK = ({name}_code, effective_start_date).
-- Note: All VARCHAR converted to STRING for Delta. All ref tables use
-- subject_area='reference' and partitioned by effective_start_date
-- (monotonic, low-cardinality growth -> efficient pruning).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Entity 1 of 16: ref_cat_event_type
-- FINRA CAT 99-event taxonomy (CAT IM v4.1.0r15) (v4.1.0r9)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_cat_event_type (
 cat_event_type_code STRING NOT NULL COMMENT 'CAT event code (e.g. MEIR, MOIR, MENO, MEOT, MEQS, MEPA)',
 cat_event_type_name STRING NOT NULL COMMENT 'Human-readable event name',
 cat_event_type_description STRING COMMENT 'Full description of the CAT event and triggering conditions',
 category STRING COMMENT 'Event category: ORDER_REQUEST, ORDER, ROUTING, MODIFICATION, EXECUTION, ALLOCATION, QUOTE, COMBINED_ORDER, REPRESENTATIVE_ORDER, MANUAL',
 lifecycle_stage STRING COMMENT 'PRE_TRADE, ORDER, EXECUTION, POST_TRADE',
 phase STRING COMMENT 'CAT phase: 2a, 2b, 2c, 2d, 2e',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date (SCD2)',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date (SCD2)',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'FINRA_CAT' COMMENT 'Authority publishing this code',
 source_version STRING COMMENT 'Version of source specification (e.g. v4.1.0r9)',
 last_updated_date DATE COMMENT 'Last update from source',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date into this table',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'FINRA CAT 99-event taxonomy (CAT IM v4.1.0r15) reference - all CAT event codes - source of truth: primary-sources/cat_im_event_types.csv (MEIR, MOIR, MENO, MONO, MEOA, MEOC, MEOT (Trade) and MEOTS (Trade Supplement), MEOTS, MEOF, MEQR, MEQS, MEPA, MEAA, MOOT, Section 5.2 multi-leg events, etc.); enforces cat_event_type enum in order_event, execution, allocation, quote_event, order_request'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'CAT event type reference - 50 events',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_cat_event_type'
);

-- Z-ORDER BY (cat_event_type_code, category)

-- ----------------------------------------------------------------------------
-- Entity 2 of 16: ref_mic
-- ISO 10383 Market Identifier Codes (~3000 entries)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_mic (
 mic_code STRING NOT NULL COMMENT 'ISO 10383 MIC code (4 chars)',
 mic_name STRING NOT NULL COMMENT 'Market name',
 mic_description STRING COMMENT 'Market description and scope',
 category STRING COMMENT 'Market category: OPRT (operating MIC), SGMT (segment MIC)',
 operating_mic STRING COMMENT 'Parent operating MIC (for segment MICs)',
 market_category_code STRING COMMENT 'NSPD, EXCH, OTHR, SINT, ATSS, APPA, RMKT, MLTF, OTHR',
 acronym STRING COMMENT 'Short acronym for the market',
 country_code STRING COMMENT 'ISO 3166-1 alpha-2 country code',
 city STRING COMMENT 'City of the market',
 website_url STRING COMMENT 'Official market website',
 status STRING COMMENT 'ACTIVE, DELETED, MODIFIED, EXPIRED',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'ISO_10383' COMMENT 'ISO Standards Organization',
 source_version STRING COMMENT 'ISO 10383 version (year-month)',
 last_updated_date DATE COMMENT 'Last monthly ISO update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'ISO 10383 Market Identifier Codes - all operating and segment MICs globally; enforces venue.mic_code, last_market, execution_venue_id lookup, and all *.mic_code references across the model'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'MIC reference - ISO 10383',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_mic'
);

-- Z-ORDER BY (mic_code, country_code, status)

-- ----------------------------------------------------------------------------
-- Entity 3 of 16: ref_country
-- ISO 3166-1 country codes (~249 entries)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_country (
 country_code STRING NOT NULL COMMENT 'ISO 3166-1 alpha-2 code (2 chars)',
 country_name STRING NOT NULL COMMENT 'Official country short name',
 country_description STRING COMMENT 'Full official country name',
 category STRING COMMENT 'Region: AMERICAS, EMEA, APAC, AFRICA',
 alpha_3_code STRING COMMENT 'ISO 3166-1 alpha-3 code (3 chars)',
 numeric_code STRING COMMENT 'ISO 3166-1 numeric code (3 digits)',
 iso_region STRING COMMENT 'ISO region classification',
 un_region STRING COMMENT 'UN M49 region',
 is_eu_member BOOLEAN COMMENT 'EU member state flag',
 is_oecd_member BOOLEAN COMMENT 'OECD member flag',
 is_fatf_member BOOLEAN COMMENT 'FATF member flag (AML)',
 is_sanctioned BOOLEAN COMMENT 'OFAC-sanctioned jurisdiction flag',
 primary_currency STRING COMMENT 'ISO 4217 primary currency',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'ISO_3166' COMMENT 'ISO',
 source_version STRING COMMENT 'ISO 3166 version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'ISO 3166-1 country codes - alpha-2, alpha-3, numeric; enforces party.country_of_incorporation, address.country_code, tax_jurisdiction.country_code, and all country references; includes sanctions/AML compliance flags'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Country reference - ISO 3166-1',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_country'
);

-- Z-ORDER BY (country_code, category, is_sanctioned)

-- ----------------------------------------------------------------------------
-- Entity 4 of 16: ref_currency
-- ISO 4217 currency codes (~180 entries)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_currency (
 currency_code STRING NOT NULL COMMENT 'ISO 4217 currency code (3 chars)',
 currency_name STRING NOT NULL COMMENT 'Currency name',
 currency_description STRING COMMENT 'Full description',
 category STRING COMMENT 'FIAT, CRYPTO, PRECIOUS_METAL, FUND, OTHER',
 numeric_code STRING COMMENT 'ISO 4217 numeric code (3 digits)',
 minor_unit INT COMMENT 'Number of decimal places (e.g. 2 for USD, 0 for JPY)',
 symbol STRING COMMENT 'Currency symbol (e.g. $, €, ¥)',
 country_code STRING COMMENT 'ISO 3166 code of issuing country',
 is_g10 BOOLEAN COMMENT 'G10 currency flag (major liquid pair)',
 is_cls_eligible BOOLEAN COMMENT 'CLS-settled currency flag',
 is_crypto BOOLEAN COMMENT 'Cryptocurrency flag',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'ISO_4217' COMMENT 'ISO',
 source_version STRING COMMENT 'ISO 4217 version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'ISO 4217 currency codes - fiat, crypto, precious metals, funds; enforces all *.currency columns (settlement_currency, position_currency, trade_currency, notional_currency, collateral_currency); tracks CLS-eligibility and G10 status'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Currency reference - ISO 4217',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_currency'
);

-- Z-ORDER BY (currency_code, category, is_g10)

-- ----------------------------------------------------------------------------
-- Entity 5 of 16: ref_cfi_category
-- ISO 10962 CFI codes (~6 top-level categories, ~1000 full codes)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_cfi_category (
 cfi_code STRING NOT NULL COMMENT 'ISO 10962 CFI code (6 chars)',
 cfi_name STRING NOT NULL COMMENT 'Instrument classification name',
 cfi_description STRING COMMENT 'Full description',
 category STRING COMMENT 'Top-level category: E (Equities), D (Debt), R (Rights), O (Options), F (Futures), S (Swaps), H (Non-listed), I (Spot), J (Forwards), K (Strategies), L (Financing), M (Others)',
 subcategory STRING COMMENT 'Second-level group',
 attribute_1 STRING COMMENT 'CFI attribute 1 (voting rights / type)',
 attribute_2 STRING COMMENT 'CFI attribute 2 (ownership / guarantee)',
 attribute_3 STRING COMMENT 'CFI attribute 3 (payment status / interest)',
 attribute_4 STRING COMMENT 'CFI attribute 4 (form / redemption)',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'ISO_10962' COMMENT 'ISO',
 source_version STRING COMMENT 'ISO 10962 version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'ISO 10962 CFI (Classification of Financial Instruments) codes - 6-character codes classifying every instrument by category, group, and 4 attributes; enforces instrument.cfi_code across all equity/debt/derivative/fund instruments'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'CFI reference - ISO 10962',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_cfi_category'
);

-- Z-ORDER BY (cfi_code, category, subcategory)

-- ----------------------------------------------------------------------------
-- Entity 6 of 16: ref_entity_legal_form
-- ISO 20275 Entity Legal Forms (ELF) (~3000 entries)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_entity_legal_form (
 elf_code STRING NOT NULL COMMENT 'ISO 20275 ELF code (4 chars)',
 elf_name STRING NOT NULL COMMENT 'Legal form name (e.g. Limited Liability Company)',
 elf_description STRING COMMENT 'Full description',
 category STRING COMMENT 'CORPORATE, PARTNERSHIP, FUND, TRUST, GOVERNMENT, INDIVIDUAL',
 country_code STRING COMMENT 'ISO 3166-1 country of jurisdiction',
 local_name STRING COMMENT 'Local-language legal form name',
 local_name_language STRING COMMENT 'ISO 639 language of local_name',
 abbreviation STRING COMMENT 'Abbreviated form (e.g. LLC, GmbH, SA, SARL)',
 is_regulated_entity BOOLEAN COMMENT 'Regulated entity flag',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'ISO_20275' COMMENT 'ISO / GLEIF',
 source_version STRING COMMENT 'ISO 20275 version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'ISO 20275 Entity Legal Forms - LLC, Corp, GmbH, SARL, PLC, LP, Trust, etc.; maintained by GLEIF; enforces party.legal_form_elf_code across all legal entities'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Entity legal form reference - ISO 20275',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_entity_legal_form'
);

-- Z-ORDER BY (elf_code, country_code, category)

-- ----------------------------------------------------------------------------
-- Entity 7 of 16: ref_order_type
-- FIX tag 40 OrdType enum
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_order_type (
 order_type_code STRING NOT NULL COMMENT 'Order type code (e.g. MARKET, LIMIT, STOP, STOP_LIMIT)',
 order_type_name STRING NOT NULL COMMENT 'Order type name',
 order_type_description STRING COMMENT 'Full description',
 category STRING COMMENT 'SIMPLE, CONDITIONAL, PEGGED, ALGO, DISCRETIONARY',
 fix_tag_40_value STRING COMMENT 'FIX 4.4 tag 40 enum value (1=Market, 2=Limit, 3=Stop, 4=StopLimit, etc.)',
 requires_price BOOLEAN COMMENT 'Requires a price field',
 requires_stop_price BOOLEAN COMMENT 'Requires a stop price',
 is_algo_order BOOLEAN COMMENT 'Algorithmic order flag',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'FIX_PROTOCOL' COMMENT 'FIX Protocol Ltd.',
 source_version STRING COMMENT 'FIX version (4.2, 4.4, 5.0 SP2)',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'FIX tag 40 OrdType enumeration - MARKET, LIMIT, STOP, STOP_LIMIT, MARKET_ON_CLOSE, LIMIT_ON_CLOSE, WITH_OR_WITHOUT, PEGGED, PREVIOUSLY_QUOTED, PREVIOUSLY_INDICATED, FUNARI, MARKET_IF_TOUCHED, NEXT_FUND_VALUATION_POINT, etc.; enforces order_event.order_type and order_request.requested_order_type'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Order type reference - FIX tag 40',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_order_type'
);

-- Z-ORDER BY (order_type_code, category)

-- ----------------------------------------------------------------------------
-- Entity 8 of 16: ref_time_in_force
-- FIX tag 59 TimeInForce enum
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_time_in_force (
 tif_code STRING NOT NULL COMMENT 'Time-in-force code (e.g. DAY, GTC, IOC, FOK, GTD, GTX, AT_OPEN, AT_CLOSE)',
 tif_name STRING NOT NULL COMMENT 'Time-in-force name',
 tif_description STRING COMMENT 'Full description',
 category STRING COMMENT 'SESSION, EXTENDED, CONDITIONAL, OPEN_ENDED',
 fix_tag_59_value STRING COMMENT 'FIX tag 59 enum value (0=Day, 1=GTC, 2=AtOpen, 3=IOC, 4=FOK, 5=GTX, 6=GTD, 7=AtClose)',
 requires_expire_date BOOLEAN COMMENT 'TRUE for GTD (requires ExpireDate tag 432)',
 auto_cancels_intraday BOOLEAN COMMENT 'TRUE for DAY / IOC / FOK',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'FIX_PROTOCOL' COMMENT 'FIX Protocol Ltd.',
 source_version STRING COMMENT 'FIX version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'FIX tag 59 TimeInForce enumeration - DAY, GTC (Good-Till-Cancel), IOC (Immediate-Or-Cancel), FOK (Fill-Or-Kill), GTD (Good-Till-Date), GTX (Good-Till-Crossing), AT_OPEN, AT_CLOSE; enforces order_event.time_in_force'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Time-in-force reference - FIX tag 59',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_time_in_force'
);

-- Z-ORDER BY (tif_code, category)

-- ----------------------------------------------------------------------------
-- Entity 9 of 16: ref_handling_instruction
-- FIX tag 21 HandlInst enum
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_handling_instruction (
 handling_instruction_code STRING NOT NULL COMMENT 'Handling instruction code',
 handling_instruction_name STRING NOT NULL COMMENT 'Name (e.g. AUTOMATED_PRIVATE, AUTOMATED_PUBLIC, MANUAL)',
 handling_instruction_description STRING COMMENT 'Full description',
 category STRING COMMENT 'AUTOMATED, MANUAL, WORKED',
 fix_tag_21_value STRING COMMENT 'FIX tag 21 enum value (1=Automated_Private_NoBroker, 2=Automated_Public_BrokerIntervention, 3=Manual)',
 requires_manual_intervention BOOLEAN COMMENT 'Requires broker intervention',
 triggers_cat_moot BOOLEAN COMMENT 'TRUE for MANUAL (triggers MOOT/MOFA CAT events)',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'FIX_PROTOCOL' COMMENT 'FIX Protocol Ltd.',
 source_version STRING COMMENT 'FIX version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'FIX tag 21 HandlInst enumeration - AUTOMATED_PRIVATE (no broker intervention), AUTOMATED_PUBLIC (broker intervention OK), MANUAL (requires human handling, triggers MOOT/MOFA); enforces order_event.order_handling_instruction'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Handling instruction reference - FIX tag 21',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_handling_instruction'
);

-- Z-ORDER BY (handling_instruction_code, category)

-- ----------------------------------------------------------------------------
-- Entity 10 of 16: ref_party_role
-- Party role taxonomy (ISSUER, CUSTOMER, BROKER, CCP, CUSTODIAN, etc.)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_party_role (
 party_role_code STRING NOT NULL COMMENT 'Party role code',
 party_role_name STRING NOT NULL COMMENT 'Role name',
 party_role_description STRING COMMENT 'Full description',
 category STRING COMMENT 'ISSUER, INVESTOR, INTERMEDIARY, INFRASTRUCTURE, REGULATOR',
 regulatory_capacity STRING COMMENT 'Capacity classification: PRINCIPAL, AGENCY, RISKLESS_PRINCIPAL, FIDUCIARY',
 requires_lei BOOLEAN COMMENT 'LEI required for this role (e.g. counterparty for EMIR/MiFIR reporting)',
 requires_crd BOOLEAN COMMENT 'CRD required (broker-dealer)',
 is_regulated_role BOOLEAN COMMENT 'Regulated role flag',
 fix_party_role_value STRING COMMENT 'FIX tag 452 PartyRole enum value (1=ExecutingFirm, 2=BrokerOfCredit, 3=ClientID, 11=OrderOriginationTrader, 12=ExecutingTrader, 13=OrderOriginationFirm, 22=EnteringFirm, 24=CustomerAccount, 38=PositionAccount, 44=RegulatoryAgency, 62=ClearingOrganization, 66=ClearingAccount, 83=ConfirmingParty, etc.)',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'INTERNAL_TAXONOMY' COMMENT 'Internal party role taxonomy (aligned with FIX 452)',
 source_version STRING COMMENT 'Taxonomy version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Party role taxonomy - CUSTOMER, ISSUER, BROKER_DEALER, INVESTMENT_MANAGER, CUSTODIAN, CCP, CLEARING_MEMBER, SWAP_DEALER, MARKET_MAKER, PRIME_BROKER, REGULATOR, etc.; enforces party_role.role_type and all *_party_role_id references'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Party role reference - FIX tag 452 aligned',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_party_role'
);

-- Z-ORDER BY (party_role_code, category)

-- ----------------------------------------------------------------------------
-- Entity 11 of 16: ref_instrument_type
-- Instrument type taxonomy (COMMON_STOCK, CORPORATE_BOND, FUTURE, OPTION, etc.)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_instrument_type (
 instrument_type_code STRING NOT NULL COMMENT 'Instrument type code',
 instrument_type_name STRING NOT NULL COMMENT 'Instrument type name',
 instrument_type_description STRING COMMENT 'Full description',
 category STRING COMMENT 'EQUITY, DEBT, DERIVATIVE, FUND, FOREX, COMMODITY, CRYPTO, STRUCTURED_PRODUCT',
 asset_class STRING COMMENT 'EQUITY, FIXED_INCOME, FX, COMMODITY, CRYPTO, RATES, CREDIT, EQUITY_DERIVATIVE',
 cfi_category_prefix STRING COMMENT 'Top-level ISO 10962 CFI prefix (E/D/R/O/F/S/H/I/J/K/L/M)',
 is_listed BOOLEAN COMMENT 'Exchange-listed flag',
 is_cleared BOOLEAN COMMENT 'CCP-cleared flag',
 is_otc BOOLEAN COMMENT 'OTC flag',
 supports_fractional BOOLEAN COMMENT 'Supports fractional trading',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'INTERNAL_TAXONOMY' COMMENT 'Internal instrument taxonomy (aligned with ISO 10962)',
 source_version STRING COMMENT 'Taxonomy version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Instrument type taxonomy - COMMON_STOCK, PREFERRED_STOCK, ADR, ETF, CORPORATE_BOND, GOVERNMENT_BOND, MUNICIPAL_BOND, FUTURE, OPTION, SWAP, FORWARD, FX_SPOT, FX_SWAP, REPO, TBA, STRUCTURED_NOTE, CRYPTO_SPOT, CRYPTO_DERIVATIVE, MUTUAL_FUND, HEDGE_FUND; enforces instrument.instrument_type'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Instrument type reference',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_instrument_type'
);

-- Z-ORDER BY (instrument_type_code, category, asset_class)

-- ----------------------------------------------------------------------------
-- Entity 12 of 16: ref_day_count
-- Day count conventions (ACT/360, 30/360, ACT/ACT, etc.)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_day_count (
 day_count_code STRING NOT NULL COMMENT 'Day count convention code (e.g. ACT_360, ACT_365, 30_360, ACT_ACT_ISDA)',
 day_count_name STRING NOT NULL COMMENT 'Convention name',
 day_count_description STRING COMMENT 'Full description of the calculation method',
 category STRING COMMENT 'ACTUAL, 30_360, BUSINESS_252',
 isda_code STRING COMMENT 'ISDA day count code (e.g. ACT/360, 30/360 German, ACT/ACT.ICMA)',
 fpml_code STRING COMMENT 'FpML scheme code',
 numerator_method STRING COMMENT 'ACTUAL, 30, 30E, 30U',
 denominator_method STRING COMMENT '360, 365, 365.25, ACTUAL',
 typical_usage STRING COMMENT 'Typical market usage (e.g. USD money market, EUR swaps, UK gilts)',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'ISDA' COMMENT 'ISDA / ICMA',
 source_version STRING COMMENT 'ISDA definitions version (2006, 2021)',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Day count conventions - ACT/360, ACT/365, 30/360 (Bond Basis), 30E/360 (Eurobond), ACT/ACT ISDA, ACT/ACT ICMA, BUS/252 (Brazilian); enforces day_count on bond, loan, swap, accrual computations'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Day count reference - ISDA',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_day_count'
);

-- Z-ORDER BY (day_count_code, category)

-- ----------------------------------------------------------------------------
-- Entity 13 of 16: ref_settlement_venue
-- Settlement venues (DTCC, Euroclear, Clearstream, Fed, CDS, JASDEC)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_settlement_venue (
 settlement_venue_code STRING NOT NULL COMMENT 'Settlement venue code',
 settlement_venue_name STRING NOT NULL COMMENT 'Venue name (e.g. DTCC, EUROCLEAR, CLEARSTREAM, FED, CDS, JASDEC)',
 settlement_venue_description STRING COMMENT 'Full description',
 category STRING COMMENT 'CSD (Central Securities Depository), ICSD (International CSD), CCP, CASH_CSD',
 country_code STRING COMMENT 'ISO 3166 country code',
 currency_code STRING COMMENT 'Primary settlement currency',
 bic_code STRING COMMENT 'ISO 9362 BIC/SWIFT code',
 supports_dvp BOOLEAN COMMENT 'DVP (Delivery vs Payment) settlement',
 supports_fop BOOLEAN COMMENT 'FOP (Free of Payment) settlement',
 supports_cns BOOLEAN COMMENT 'CNS (Continuous Net Settlement) - NSCC only',
 t_plus_standard INT COMMENT 'Standard T+n settlement cycle (1 for US post-May-2024)',
 operating_hours_utc STRING COMMENT 'Operating hours in UTC',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'INTERNAL_TAXONOMY' COMMENT 'Internal settlement venue taxonomy',
 source_version STRING COMMENT 'Taxonomy version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Settlement venue reference - CSDs and ICSDs (DTCC, EUROCLEAR, CLEARSTREAM, FED_RESERVE, CDS_CANADA, JASDEC, HKSCC, KSEI, NSDL, ESES), CCPs (NSCC, OCC, ICE_CLEAR, LCH, CME_CLEARING, FICC); enforces settlement_instruction.settlement_venue'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Settlement venue reference',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_settlement_venue'
);

-- Z-ORDER BY (settlement_venue_code, country_code, category)

-- ----------------------------------------------------------------------------
-- Entity 14 of 16: ref_regulator
-- Global regulators (SEC, FINRA, ESMA, FCA, MAS, HKMA, JFSA, CFTC, OCC)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_regulator (
 regulator_code STRING NOT NULL COMMENT 'Regulator code (e.g. SEC, FINRA, CFTC, OCC, ESMA, FCA, BaFin, MAS, HKMA, JFSA, ASIC, OSC, CSA)',
 regulator_name STRING NOT NULL COMMENT 'Regulator full name',
 regulator_description STRING COMMENT 'Full description',
 category STRING COMMENT 'SECURITIES, BANKING, COMMODITIES, INSURANCE, AML, DATA_PROTECTION',
 country_code STRING COMMENT 'ISO 3166 country code',
 jurisdiction_scope STRING COMMENT 'NATIONAL, FEDERAL, STATE, SUPRANATIONAL',
 primary_statute STRING COMMENT 'Primary governing statute (e.g. Exchange Act 1934, MiFID II, Dodd-Frank)',
 reporting_regimes STRING COMMENT 'Comma-separated regimes administered (e.g. CAT,TRF,BLUESHEETS,13F,13H)',
 lei_required BOOLEAN COMMENT 'Requires LEI for reporting entities',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'INTERNAL_TAXONOMY' COMMENT 'Internal regulator taxonomy',
 source_version STRING COMMENT 'Taxonomy version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Regulator reference - SEC, FINRA, CFTC, OCC, ESMA, FCA, BaFin, AMF, MAS, HKMA, JFSA, ASIC, OSC, CSA, CNMV, Consob, AFM; enforces regulatory_report.regulator_code and regulatory_hold.regulator_code'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Regulator reference',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_regulator'
);

-- Z-ORDER BY (regulator_code, country_code, category)

-- ----------------------------------------------------------------------------
-- Entity 15 of 16: ref_credit_rating_scale
-- Credit rating scales (S&P, Moody's, Fitch, DBRS)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_credit_rating_scale (
 credit_rating_code STRING NOT NULL COMMENT 'Credit rating code (e.g. AAA, AA+, Baa1, BBB-, C, D)',
 credit_rating_name STRING NOT NULL COMMENT 'Rating name',
 credit_rating_description STRING COMMENT 'Full description of credit quality',
 category STRING COMMENT 'INVESTMENT_GRADE, HIGH_YIELD, DEFAULTED, NOT_RATED',
 rating_agency STRING NOT NULL COMMENT 'Rating agency: SP (S&P), MOODYS, FITCH, DBRS, JCR, R_AND_I, SCOPE, KROLL',
 agency_scale STRING NOT NULL COMMENT 'LONG_TERM, SHORT_TERM, ISSUER, ISSUE, RECOVERY',
 numeric_equivalent INT COMMENT 'Internal numeric equivalent (1=AAA, descending)',
 basel_risk_weight DECIMAL(8,4) COMMENT 'Basel III standardized risk weight (0.0-1.5)',
 default_probability DECIMAL(10,8) COMMENT 'Historical 1-year cumulative default probability',
 is_investment_grade BOOLEAN COMMENT 'Investment grade flag (AAA-BBB- / Aaa-Baa3)',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL COMMENT 'Rating agency (SP, MOODYS, FITCH, DBRS)',
 source_version STRING COMMENT 'Methodology version',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Credit rating scales - S&P (AAA/AA+/AA/AA-/A+/A/A-/BBB+/BBB/BBB-/BB+/BB/BB-/B+/B/B-/CCC+/CCC/CCC-/CC/C/D), Moody''s (Aaa/Aa1/Aa2/Aa3/A1/A2/A3/Baa1/Baa2/Baa3/Ba1/Ba2/Ba3/B1/B2/B3/Caa1/Caa2/Caa3/Ca/C), Fitch, DBRS; enforces party.credit_rating and instrument.credit_rating references; includes Basel risk weights'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Credit rating scale reference',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_credit_rating_scale'
);

-- Z-ORDER BY (credit_rating_code, rating_agency, is_investment_grade)

-- ----------------------------------------------------------------------------
-- Entity 16 of 16: ref_tax_jurisdiction
-- Tax jurisdictions and withholding treaty rates
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_tax_jurisdiction (
 tax_jurisdiction_code STRING NOT NULL COMMENT 'Tax jurisdiction code',
 tax_jurisdiction_name STRING NOT NULL COMMENT 'Jurisdiction name',
 tax_jurisdiction_description STRING COMMENT 'Full description',
 category STRING COMMENT 'FEDERAL, STATE, PROVINCIAL, MUNICIPAL, SUPRANATIONAL',
 country_code STRING COMMENT 'ISO 3166 country code',
 subdivision_code STRING COMMENT 'ISO 3166-2 subdivision code (state/province)',
 tax_authority STRING COMMENT 'Administering authority (e.g. IRS, HMRC, CRA, BMF)',
 tax_id_format STRING COMMENT 'Tax ID format (e.g. EIN, SSN, NINO, SIN, UTR, NIF)',
 default_withholding_rate DECIMAL(8,4) COMMENT 'Default non-treaty withholding rate (0.0-1.0)',
 treaty_withholding_rate DECIMAL(8,4) COMMENT 'US treaty withholding rate for qualifying holders',
 fatca_participant BOOLEAN COMMENT 'FATCA IGA participant flag',
 crs_participant BOOLEAN COMMENT 'OECD Common Reporting Standard participant flag',
 is_treaty_jurisdiction BOOLEAN COMMENT 'Has double-taxation treaty with US',
 effective_start_date DATE NOT NULL COMMENT 'Effective start date',
 effective_end_date DATE NOT NULL DEFAULT DATE'9999-12-31' COMMENT 'Effective end date',
 is_active BOOLEAN NOT NULL COMMENT 'Active flag',
 source_authority STRING NOT NULL DEFAULT 'OECD_IRS' COMMENT 'OECD / IRS / local tax authorities',
 source_version STRING COMMENT 'Taxonomy version / tax year',
 last_updated_date DATE COMMENT 'Last source update',
 record_source STRING NOT NULL COMMENT 'Source system lineage identifier',
 load_date TIMESTAMP NOT NULL DEFAULT current_timestamp COMMENT 'Load date',
 _created_at TIMESTAMP COMMENT 'CDF audit',
 _updated_at TIMESTAMP COMMENT 'CDF audit'
)
STORED AS PARQUET
COMMENT 'Tax jurisdiction reference - US federal+state, UK, Canadian federal+provincial, EU member states, LatAm, APAC; includes default and treaty withholding rates, FATCA/CRS participation; enforces party.tax_jurisdiction_code'
PARTITIONED BY (effective_start_date)
TBLPROPERTIES (
 'description' = 'Tax jurisdiction reference',
 'parquet.compression' = 'ZSTD',
 'subject_area' = 'reference',
 'source_lineage' = ' section Reference Tables - ref_tax_jurisdiction'
);

-- Z-ORDER BY (tax_jurisdiction_code, country_code, category)

-- ============================================================================
-- END OF FILE - 16 CREATE TABLE statements
-- ============================================================================
